// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4859.potatobot2;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.RobotDrive;
import com.ctre.phoenix.sensors.PigeonIMU;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX drivetrainLeftMotor;
    public static WPI_TalonSRX drivetrainRightMotor;
    public static WPI_TalonSRX drivetrainPigeonMotor;
    public static RobotDrive drivetrainRobotDrive;
    public static PigeonIMU drivetrainPigeonIMU;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainLeftMotor = new WPI_TalonSRX(5);
        
        
        drivetrainRightMotor = new WPI_TalonSRX(2);
        drivetrainPigeonMotor = new WPI_TalonSRX(6);
        
        drivetrainRobotDrive = new RobotDrive(drivetrainLeftMotor, drivetrainRightMotor);
        drivetrainPigeonIMU = new PigeonIMU(drivetrainPigeonMotor);
        drivetrainRobotDrive.setSafetyEnabled(true);
        // drivetrainRobotDrive.setExpiration(0.1);
        // drivetrainRobotDrive.setSensitivity(0.5);
        // drivetrainRobotDrive.setMaxOutput(1.0);



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
